port: "8080"

db:
    username: "postgres"
    host: "localhost"
    port: "5432"
    dbname: "postgres"
    sslmode: "disable"
    password: "-"

stripe:
  secret_key: "-"

twilio:
    account_sid: "-"
    auth_token: "-"
    from: "+1234567890"